%YAML:1.0
use_ros: 1 # if 1 set your image_topic,else 0 set your image path
image_topic: "/camera/color/image_raw"
depth_image_topic: "/camera/depth/image_rect_raw"
image_path: "/home/hnu/whd_data"
# tensorrt init parameters
yolov11_tensorrt_config:
  kGpuId: 0
  kNumClass: 1
  kInputH: 640
  kInputW: 640
  kNmsThresh: 0.65
  kConfThresh: 0.5
  kMaxNumOutputBbox: 50 # assume the box outputs no more than kMaxNumOutputBbox boxes that conf >= kNmsThresh
  kNumBoxElement: 7 # left, top, right, bottom, confidence, class, keepflag(whether drop when NMS)
  use_FP16_Mode: 1 # FP16 mode
  use_INT8_Mode: 0 # INT8 mode
  cacheFile: "./int8.cache"
  calibrationDataPath: "../calibrator"

  onnxFile: "/home/hnu/experiment/lv_dot/src/onboard_detector/onnx_model/yolov11n_v2.onnx" # please export onnx to float32
  trtFile: "/home/hnu/experiment/lv_dot/src/onboard_detector/onnx_model/yolov11n_v2.plan" # if has't .plan,first will creat on trtFile
  # detect classes name
  vClassNames:
    - "drone"

output_path: "/home/hnu/experiment/lv_dot/src/onboard_detector"